name: buzzcab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1 # Use the latest version
  shared_preferences: ^2.3.3
  iconsax: ^0.0.8

  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1
  lottie: ^3.1.3
  data_table_2: ^2.5.15
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.16
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/icons/homepage/
    - assets/icons/Vector.svg
    - assets/icons/
    - assets/images/content/choosepath.png
    - assets/images/animations/f078240be4398f332e5a2eaaed88e9d0.gif
    - assets/images/content/Frame 267.svg
    - assets/images/content/Group 53.svg

 