name: buzzcab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  iconsax: ^0.0.8
  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1
  lottie: ^3.1.3
  data_table_2: ^2.5.15
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.15
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0  # Added missing version
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image: ^4.3.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  google_maps_flutter: ^2.10.0
  flutter_google_maps_webservices: ^1.1.1
  google_places_flutter: ^2.0.6
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  flutter_dash: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/content/IMG_5195.png
    - assets/images/animations/
    - assets/icons/car_icon.png
    - assets/icons/payment_methods/
    - assets/icons/homepage/
    - assets/icons/
    - assets/images/content/choosepath.png
    - assets/images/animations/f078240be4398f332e5a2eaaed88e9d0.gif
    - assets/icons/Frame_car.svg
    - assets/icons/Frame_logout.svg